{
	"name": "pl_m_dataflow_HandlingError",
	"properties": {
		"activities": [
			{
				"name": "goodvserror",
				"type": "ExecuteDataFlow",
				"dependsOn": [],
				"policy": {
					"timeout": "1.00:00:00",
					"retry": 0,
					"retryIntervalInSeconds": 30,
					"secureOutput": false,
					"secureInput": false
				},
				"userProperties": [],
				"typeProperties": {
					"dataflow": {
						"referenceName": "df_ErrorrowHandleDF",
						"type": "DataFlowReference"
					},
					"compute": {
						"coreCount": 8,
						"computeType": "General"
					},
					"traceLevel": "Coarse"
				}
			}
		],
		"annotations": [],
		"lastPublishTime": "2021-10-23T18:34:41Z"
	},
	"type": "Microsoft.DataFactory/factories/pipelines"
}